fix: [#65677] Set up `LIBSASS_ADDITIONAL_INCLUDE_PATHS` to find BS SCSS mixins
Without this setting, `django_libsass` uses the `STATICFILES_FINDERS`
setting to find the relevant `.scss` files when compiling SCSS to CSS.

In production environment, this caused the following error:

```
>>> from django_libsass import compile
>>> from django.templatetags.static import static
>>>
>>> compile(**{
...     'custom_functions': {'static': static},
...     'filename':
'/usr/local/lib/python3.11/site-packages/told_common/static/bootstrap/theme.scss',
...     'include_paths':
['/usr/local/lib/python3.11/site-packages/told_common/static',
'/usr/local/lib/python3.11/site-packages/django_bootstrap_icons/static'],
...     'output_style': 'compressed',
...     'source_comments': True
... })
Traceback (most recent call last):
  File "<console>", line 1, in <module>
File "/usr/local/lib/python3.11/site-packages/django_libsass.py", line
135, in compile
    output = sass.compile(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/sass.py", line 725, in
compile
    raise CompileError(v)
sass.CompileError: Error: File to import not found or unreadable:
mixins/banner.
on line 1:1 of
../../../usr/local/lib/python3.11/site-packages/told_common/static/bootstrap/scss/bootstrap.scss
from line 50:1 of
../../../usr/local/lib/python3.11/site-packages/told_common/static/bootstrap/theme.scss
>> @import "mixins/banner";

   ^
```

It turns out that
`/usr/local/lib/python3.11/site-packages/told_common/static/bootstrap/scss/`
does not include the required `mixins` folder, while
`/app/told-common/told_common/static/bootstrap/scss/` does.
`